### ISSUE TITLE
Not enough information in error message for `invalid json`

### ISSUE THREAD

**Issue by SkReD** [th0r/npm-upgrade#33]
This all that outputed when parsing of json fails. Full path to parsed file should be enough.
```
Checking for outdated dependencies filtered with @boxy/* for "C:\CSSSR\portal-web\package.json"...

[====================] 745/748 99%SyntaxError: Unexpected end of JSON input while parsing near '...eact-spring/sponsor/0'
    at JSON.parse (<anonymous>)
    at parseJson (C:\Users\Mikhail\AppData\Roaming\npm-cache\_npx\13788\node_modules\npm-upgrade\node_modules\json-parse-better-errors\index.js:7:17)
    at consumeBody.call.then.buffer (C:\Users\Mikhail\AppData\Roaming\npm-cache\_npx\13788\node_modules\npm-upgrade\node_modules\node-fetch-npm\src\body.js:96:50)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by th0r** [comment]
This package doesn't "own" this error - it comes from the `pacote` package when it tries to fetch some meta information. This error doesn't contain any extra information so I don't know how we can improve it.

**Comment by th0r** [comment]
Closed due to inactivity.
