### ISSUE TITLE
Bypass SSL security for internal use

### ISSUE THREAD

**Issue by jkeruzec** [th0r/npm-upgrade#54]
Hi,

We have an issue :
npm-upgrade 2.0.3

```
npm-upgrade
Checking for outdated dependencies for "package.json"...
[--------------------] 0/64 0%(node:9572) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
FetchError: request to https://nexus/repository/npm-all/@date-io%2fdate-fns failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (\npm\node_modules\npm-upgrade\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  type: 'system'
}
```

How can I disable https certification verification ? 
Thanks,

**Comment by th0r** [comment]
Error happens in `minipass-fetch` module which is, according to `npm ls minipass-fetch`, is used by `npm-check-updates => pacote` module:
```
npm-upgrade@2.0.4 /Volumes/Work/npm-upgrade
└─┬ npm-check-updates@4.0.3
  └─┬ pacote@11.1.0
    ├── minipass-fetch@1.2.1
    └─┬ npm-registry-fetch@8.0.0
      ├─┬ make-fetch-happen@8.0.2
      │ └── minipass-fetch@1.2.1  deduped
      └── minipass-fetch@1.2.1  deduped
```
So it's better to ask [here](https://github.com/npm/pacote) about this error.

**Comment by th0r** [comment]
@jkeruzec any news?

**Comment by th0r** [comment]
Closed due to inactivity.
